[package]
name = "personal-website"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.5", features = ["ssr"] }
leptos_meta = { version = "0.8.5", features = ["ssr"] }
leptos_router = { version = "0.8.5", features = ["ssr"] }
leptos_axum = "0.8.5"
leptos_config = "0.8.5"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros"] }
pulldown-cmark = "0.13"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

# rust-ui dependencies
leptos_ui = "0.3"
tw_merge = { version = "0.1.17", features = ["variant"] }
icons = { version = "0.18.0", features = ["leptos"] }

[package.metadata.leptos]
output-name = "personal-website"
site-root = "target/site"
tailwind-input-file = "style/tailwind.css"
